# This is just the default starship prompt_order with some items commented out.
prompt_order = [
    "username",
    "hostname",
    "kubernetes",
    "directory",
    "git_branch",
    "git_commit",
    "git_state",
    "git_status",
    "hg_branch",
    "docker_context",
    "package",
    "dotnet",
    "elixir",
    "elm",
    "erlang",
    # "golang",
    "java",
    "julia",
    "nim",
    "nodejs",
    "ocaml",
    "php",
    "purescript",
    "python",
    "ruby",
    # "rust",
    "terraform",
    "zig",
    "nix_shell",
    "conda",
    "memory_usage",
    # "aws",
    "env_var",
    "crystal",
    "cmd_duration",
    "custom",
    # "line_break",
    # "jobs",        # Seems to be buggy. It was showing 1 job when there weren't any.
    "battery",
    "time",
    "character",
]

[time]
disabled = false
